server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: Feedback-service
          uri: lb:http://FEEDBACK-SERVICE
          predicates:
            - Path=/api/v1/feedbacks/**
